### ISSUE TITLE
500 Error when creating new transactions

### ISSUE THREAD

**Issue by willyogo** [cosmos/cosmos-multisig-ui#137]
gm again friends :)

I'm currently getting a 500 error when attempting to create a delegation transaction.

<img width="1168" alt="image" src="https://github.com/cosmos/cosmos-multisig-ui/assets/26232238/78ed4c54-5566-4664-96d2-814aa9202791">

**Comment by webmaster128** [comment]
Thank you for the report! This is a server error from vercel (HTTP 500) when pushing the transaction. This is not easy to debug for us since the deployment is currently using ICF's Vercel account. We tested it for a MsgDelegate on a different network and that worked.

Since this might be a temporary server side issue (on Vercel or Fauna), it could be a temporary thing. Could you try it again and check if it still fails with the same error?

**Comment by willyogo** [comment]
It's working now @webmaster128! Thanks for the guidance and for building and maintaining this.

One last suggestion while I'm here that you've probably already thought of:
Currently the default gas limit for all transactions is 200,000. This will cause transactions such as delegations to fail because a delegation tx from a 2/2 consumes ~205k gas ([example tx](cosmosvaloper199mlc7fr6ll5t54w7tts7f4s0cvnqgc59nmuxf))

This isn't too bad to workaround by just manually updating the gas limit each time, but it would be awesome if the app automatically set the gas limit to a sufficient level or any given tx.

thanks again!

**Comment by webmaster128** [comment]
> One last suggestion while I'm here that you've probably already thought of:
Currently the default gas limit for all transactions is 200,000. This will cause transactions such as delegations to fail because a delegation tx from a 2/2 consumes ~205k gas ([example tx](https://github.com/cosmos/cosmos-multisig-ui/issues/cosmosvaloper199mlc7fr6ll5t54w7tts7f4s0cvnqgc59nmuxf))

> This isn't too bad to workaround by just manually updating the gas limit each time, but it would be awesome if the app automatically set the gas limit to a sufficient level or any given tx.

This is VERY helpful. We now calculate the gas limit dynamic (fixed amount for the whole tx + fixed amount per message depending on its type). Couly you post all info into a new ticket (tx link seems missing)? Then we can look into it closely.

This topic is done I'd say.

**Comment by willyogo** [comment]
you bet, just created a new issue: https://github.com/cosmos/cosmos-multisig-ui/issues/141

thanks again! 💜
