### ISSUE TITLE
Forked cosmos-multisig-ui to add some lava custom transactions fetching /api/chain/[chain-id]/multisig doesnt work 

### ISSUE THREAD

**Issue by ranlavanet** [cosmos/cosmos-multisig-ui#202]
Hey just tried to fork the multisig project, and the /api/chain/[chain-id]/multisig doesnt work for lava-testnet-2 

any idea what could be the issue? 

this is the repo: 
https://github.com/lavanet/lava-multisig-ui

this is the error: 
<img width="490" alt="image" src="https://github.com/cosmos/cosmos-multisig-ui/assets/106548467/1e29dfb6-2b3c-4aa3-bc20-6b8875029a52">

**Comment by abefernan** [comment]
@ranlavanet hi, do the database queries work from your Dgraph dashboard?

**Comment by ranlavanet** [comment]
seems like it does:
<img width="1094" alt="image" src="https://github.com/cosmos/cosmos-multisig-ui/assets/106548467/3a2f2f57-3d59-4fee-989f-2754cd589d7a">

**Comment by abefernan** [comment]
There's something weird: it says "cannot read properties of undefined (reading 'createMultisig')". But for me (if I use your endpoint) it says 'addMultisig'. Any chance you changed that name somewhere?

No reference to 'createMultisig' should be found in Dgraph, since there the auto-generated function is called 'addMultisig'.

**Comment by ranlavanet** [comment]
I will try to validate closing for now, if i need additional help i will try 🙂 thanks
